# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - info
  - enhancement
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has not had activity in two months, is it still a problem? Let us know here asap!
  As seven days after this comment has been posted, the issue will be closed and marked as stale!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
